---
title: "Testing in California"
author: "Tri Truong"
date: "6/2/2020"
output: 
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = NA, 
                      message = FALSE, warning = FALSE,
                      fig.height=6, fig.width = 9, fig.align = "center")
```

# Packages

```{r load-packages, message = FALSE}
library(stringr)
library(dplyr)
library(pdftools)
library(tidyverse)
library(pdftables)
library(qpdf)
library(rJava)
library(tabulizer)
library(tabulizerjars)
```

# PDF

```{r load_pdf_Alabama}
pdf_subset("1941.Directory of electric utilities in the US pdf.pdf", page= 122:141, output= "California_subset.pdf")
```


```{r}
california_file <- tabulizer::extract_text("California_subset.pdf")
california_file2 <- str_split(california_file, "\n")
california_file3 <- california_file2[[1]]
experiment_california <- california_file3[4:103]
final_california_file <- california_file3[104:length(california_file3)]
```


```{r}
for (i in 1:length(experiment_california)) {
  if(str_detect(experiment_california[i], "04-") == FALSE & !is.na(experiment_california[i])) {
    experiment_california[i] <- paste(experiment_california[i], experiment_california[i+1], sep = "")
    experiment_california[i+1] <- NA
  }
}
experiment_california <- experiment_california %>%
  na.omit()
```

```{r}
california_index_company_name <- vector(mode="character", length=11)
california_index_company_code <- vector(mode="character", length=11)

tracking_number <- 1

for (i in 1:length(experiment_california)) {
  string <- experiment_california[i]
  m <- gregexpr('[0-9]+',string)
  something <- regmatches(string, m)
  something <- c(something[[1]])
  california_index_company_code[tracking_number] <- paste(something, collapse = '-')
  vector_string <- str_split(string, "04")
  vector_string <- vector_string[[1]]
  california_index_company_name[tracking_number] <- vector_string[1]
  tracking_number <- tracking_number + 1
}

table_california_index <- data.frame(california_index_company_name, california_index_company_code)
write.csv(table_california_index, file = "california_index.csv")
```

```{r}
vector_company <- vector(mode="character", length=11)
vector_company_copy <- vector(mode="character", length=1)

company_position <- 1
last_position <- 1
track_vector <- 1
tracking_data_frame <- 1

california_company_code <- vector(mode="character")
california_company_name <- vector(mode="character")
california_company_eup <- vector(mode="character")
california_company_eor <- vector(mode="character")
california_company_ec <- vector(mode="character")
california_company_p <- vector(mode="character")
```

```{r}
for (i in 3:length(final_california_file)) {
  if (str_detect(final_california_file[i], '04-')) {
    california_companies <- final_california_file[last_position:i-1]
    
    track_vector2 <- 1
    
    for (k in 1:length(california_companies)) {
      if (str_detect(california_companies[k], '04-')) {
        vector_company[track_vector] <- california_companies[k]
        vector_company[track_vector+1] <- california_companies[k+1]
        track_vector <- track_vector + 2
        
        vector_company_copy[track_vector2] <- california_companies[k]
        vector_company_copy[track_vector2 + 1] <- california_companies[k+1]
        track_vector2 <- track_vector2 + 2
      }
      
      if (str_detect(california_companies[k], "Electric Utility Plant")) {
        vector_company[track_vector] <- california_companies[k]
        track_vector <- track_vector + 1
        
        vector_company_copy[track_vector2] <- california_companies[k]
        track_vector2 <- track_vector2 + 1
      }
      
      if (str_detect(california_companies[k], "Electric Operating Revenues")) {
        vector_company[track_vector] <- california_companies[k]
        track_vector <- track_vector + 1
        
        vector_company_copy[track_vector2] <- california_companies[k]
        track_vector2 <- track_vector2 + 1
      }
      
      if (str_detect(california_companies[k], "Electric Customers")) {
        vector_company[track_vector] <- california_companies[k]
        track_vector <- track_vector + 1
        
        vector_company_copy[track_vector2] <- california_companies[k]
        track_vector2 <- track_vector2 + 1
      }
      
      if(str_detect(california_companies[k], "Purchased")) {
        vector_company[track_vector] <- california_companies[k]
        track_vector <- track_vector + 1
        
        vector_company_copy[track_vector2] <- california_companies[k]
        track_vector2 <- track_vector2 + 1
      }
    #  break
    }
    
    california_company_code[tracking_data_frame] <- vector_company_copy[1]
    california_company_name[tracking_data_frame] <- vector_company_copy[2]
    
    if(str_detect(vector_company_copy[3], "Electric Utility Plant")) {
      california_company_eup[tracking_data_frame] <- vector_company_copy[3]
    } else {
      california_company_eup[tracking_data_frame] <- NA
    }
    
    if(str_detect(vector_company_copy[4], "Electric Operating Revenues")) {
      california_company_eor[tracking_data_frame] <- vector_company_copy[4]
    } else {
      california_company_eor[tracking_data_frame] <- NA
    }
    
    if(str_detect(vector_company_copy[5], "Electric Customers")) {
      california_company_ec[tracking_data_frame] <- vector_company_copy[5]
    } else {
      california_company_ec[tracking_data_frame] <- NA
    }
    
    if(str_detect(vector_company_copy[6], "Purchased")) {
      california_company_p[tracking_data_frame] <- vector_company_copy[6]
    } else {
      california_company_p[tracking_data_frame] <- NA
    }

    tracking_data_frame <- tracking_data_frame + 1
    company_position <- company_position + 1
    last_position <- i+1
  }
}
```


```{r}
for (i in 1:length(california_company_code)) {
  if (startsWith(california_company_code[i], "0") == FALSE) {
    california_company_code[i] <- gsub("(?<=\\()[^()]*(?=\\))(*SKIP)(*F)|.", "", 
                                     california_company_code[i], perl=T)
  }
}


for (i in 1:length(california_company_eup)) {
  string <- california_company_eup[i]
  string_vector <- str_split(string, "\\$")
  california_company_eup[i] <- string_vector[[1]][2]
}

for (i in 1:length(california_company_eup)) {
  string <- california_company_eup[i]
  m <- gregexpr('[0-9]+',string)
  something <- regmatches(string, m)
  something <- c(something[[1]])
  california_company_eup[i] <- paste(something, collapse = '')
}

for (i in 1:length(california_company_eup)) {
  if (california_company_eup[i] == "") {
    california_company_eup[i] <- NA
  }
}

for (i in 1:length(california_company_eor)) {
  string <- california_company_eor[i]
  string_vector <- str_split(string, "\\$")
  california_company_eor[i] <- string_vector[[1]][2]
}

for (i in 1:length(california_company_eor)) {
  string <- california_company_eor[i]
  m <- gregexpr('[0-9]+',string)
  something <- regmatches(string, m)
  something <- c(something[[1]])
  california_company_eor[i] <- paste(something, collapse = '')
}

for (i in 1:length(california_company_eor)) {
  if (california_company_eor[i] == "") {
    california_company_eor[i] <- NA
  }
}


for (i in 1:length(california_company_ec)) {
  string <- california_company_ec[i]
  m <- gregexpr('[0-9]+',string)
  something <- regmatches(string, m)
  something <- c(something[[1]])
  california_company_ec[i] <- paste(something, collapse = '')
}

for (i in 1:length(california_company_ec)) {
  if (california_company_ec[i] == "") {
    california_company_ec[i] <- NA
  }
}


for (i in 1:length(california_company_p)) {
  string <- california_company_p[i]
  m <- gregexpr('[0-9]+',string)
  something <- regmatches(string, m)
  something <- c(something[[1]])
  california_company_p[i] <- paste(something, collapse = '')
}

for (i in 1:length(california_company_p)) {
  if (california_company_p[i] == "") {
    california_company_p[i] <- NA
  }
}
```

```{r}
state_name <- "California"
table_california_company2 <- data.frame(california_company_name, state_name, 
                                     california_company_code, 
                                     california_company_eup, california_company_eor,
                                     california_company_ec, california_company_p)

colnames(table_california_company2) = c("Company Name", "State", "Company Code", 
                                     "Electric Utility Plant (dollars)", 
                                     "Electric Operating Revenues (dollars)",
                                     "Electric Customers", 
                                     "Energy Purchased (Kilowatt/hour)")

write.csv (table_california_company2, file = paste0('california_table_company_1941', '.csv'))
```

