---
title: "Testing in Connecticut"
author: "Tri Truong"
date: "6/2/2020"
output: 
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = NA, 
                      message = FALSE, warning = FALSE,
                      fig.height=6, fig.width = 9, fig.align = "center")
```

# Packages

```{r load-packages, message = FALSE}
library(stringr)
library(dplyr)
library(pdftools)
library(tidyverse)
library(pdftables)
library(qpdf)
library(rJava)
library(tabulizer)
library(tabulizerjars)
```

# PDF

```{r load_pdf_Alabama}
pdf_subset("1941.Directory of electric utilities in the US pdf.pdf", page= 156:163, output= "Connecticut_subset.pdf")
```


```{r}
connecticut_file <- tabulizer::extract_text("Connecticut_subset.pdf")
connecticut_file2 <- str_split(connecticut_file, "\n")
connecticut_file3 <- connecticut_file2[[1]]
final_connecticut_file <- connecticut_file3[57:length(connecticut_file3)]
```


```{r}
vector_company <- vector(mode="character", length=11)

company_position <- 1
last_position <- 1
track_vector <- 1
tracking_data_frame <- 1

connecticut_company_code <- vector(mode="character")
connecticut_company_name <- vector(mode="character")
connecticut_company_eup <- vector(mode="character")
connecticut_company_eor <- vector(mode="character")
connecticut_company_ec <- vector(mode="character")
connecticut_company_p <- vector(mode="character")


for (i in 3:length(final_connecticut_file)) {
  if (str_detect(final_connecticut_file[i], '06-')) {
    connecticut_companies <- final_connecticut_file[last_position:i-1]
    
    vector_company_copy <- vector(mode="character", length=1)
    
    for (k in 1:length(connecticut_companies)) {
      if (str_detect(connecticut_companies[k], '06-')) {
        vector_company[track_vector] <- connecticut_companies[k]
        vector_company[track_vector+1] <- connecticut_companies[k+1]
        track_vector <- track_vector + 2
        
        vector_company_copy[1] <- connecticut_companies[k]
        vector_company_copy[2] <- connecticut_companies[k+1]
      }
      
      if (str_detect(connecticut_companies[k], "Utility Plant")) {
        vector_company[track_vector] <- connecticut_companies[k]
        track_vector <- track_vector + 1
        
        vector_company_copy[3] <- connecticut_companies[k]
      }
      
      if (str_detect(connecticut_companies[k], "Operating Revenue")) {
        vector_company[track_vector] <- connecticut_companies[k]
        track_vector <- track_vector + 1
        
        vector_company_copy[4] <- connecticut_companies[k]
      }
      
      if (str_detect(connecticut_companies[k], "Customers")) {
        vector_company[track_vector] <- connecticut_companies[k]
        track_vector <- track_vector + 1
        
        vector_company_copy[5] <- connecticut_companies[k]
      }
      
      if(str_detect(connecticut_companies[k], "Purchased")) {
        vector_company[track_vector] <- connecticut_companies[k]
        track_vector <- track_vector + 1
        
        vector_company_copy[6] <- connecticut_companies[k]
      }
    }
   
    connecticut_company_code[tracking_data_frame] <- vector_company_copy[1]
    connecticut_company_name[tracking_data_frame] <- vector_company_copy[2]
    
    if(str_detect(vector_company_copy[3], "Utility Plant") & !is.na(vector_company_copy[3])) {
      connecticut_company_eup[tracking_data_frame] <- vector_company_copy[3]
    } else {
      connecticut_company_eup[tracking_data_frame] <- NA
    }
    
   if(str_detect(vector_company_copy[4], "Operating Revenue") & !is.na(vector_company_copy[4])) {
     connecticut_company_eor[tracking_data_frame] <- vector_company_copy[4]
   } else {
     connecticut_company_eor[tracking_data_frame] <- NA
   }
 
   if(str_detect(vector_company_copy[5], "Customers") & !is.na(vector_company_copy[5])) {
     connecticut_company_ec[tracking_data_frame] <- vector_company_copy[5]
   } else {
     connecticut_company_ec[tracking_data_frame] <- NA
   }
 
   if(str_detect(vector_company_copy[6], "Purchased") & !is.na(vector_company_copy[6])) {
     connecticut_company_p[tracking_data_frame] <- vector_company_copy[6]
   } else {
     connecticut_company_p[tracking_data_frame] <- NA
   }

    tracking_data_frame <- tracking_data_frame + 1
    company_position <- company_position + 1
    last_position <- i+1
  }
}
```


```{r}
for (i in 1:length(connecticut_company_code)) {
  if (startsWith(connecticut_company_code[i], "0") == FALSE) {
    connecticut_company_code[i] <- gsub("(?<=\\()[^()]*(?=\\))(*SKIP)(*F)|.", "", 
                                     connecticut_company_code[i], perl=T)
  }
}

for (i in 1:length(connecticut_company_eup)) {
  string <- connecticut_company_eup[i]
  string_vector <- str_split(string, "\\$")
  connecticut_company_eup[i] <- string_vector[[1]][2]
}

for (i in 1:length(connecticut_company_eup)) {
  string <- connecticut_company_eup[i]
  m <- gregexpr('[0-9]+',string)
  something <- regmatches(string, m)
  something <- c(something[[1]])
  connecticut_company_eup[i] <- paste(something, collapse = '')
}

for (i in 1:length(connecticut_company_eup)) {
  if (connecticut_company_eup[i] == "") {
    connecticut_company_eup[i] <- NA
  }
}

for (i in 1:length(connecticut_company_eor)) {
  string <- connecticut_company_eor[i]
  string_vector <- str_split(string, "\\$")
  connecticut_company_eor[i] <- string_vector[[1]][2]
}

for (i in 1:length(connecticut_company_eor)) {
  string <- connecticut_company_eor[i]
  m <- gregexpr('[0-9]+',string)
  something <- regmatches(string, m)
  something <- c(something[[1]])
  connecticut_company_eor[i] <- paste(something, collapse = '')
}

for (i in 1:length(connecticut_company_eor)) {
  if (connecticut_company_eor[i] == "") {
    connecticut_company_eor[i] <- NA
  }
}


for (i in 1:length(connecticut_company_ec)) {
  string <- connecticut_company_ec[i]
  m <- gregexpr('[0-9]+',string)
  something <- regmatches(string, m)
  something <- c(something[[1]])
  connecticut_company_ec[i] <- paste(something, collapse = '')
}

for (i in 1:length(connecticut_company_ec)) {
  if (connecticut_company_ec[i] == "") {
    connecticut_company_ec[i] <- NA
  }
}


for (i in 1:length(connecticut_company_p)) {
  string <- connecticut_company_p[i]
  m <- gregexpr('[0-9]+',string)
  something <- regmatches(string, m)
  something <- c(something[[1]])
  connecticut_company_p[i] <- paste(something, collapse = '')
}

for (i in 1:length(connecticut_company_p)) {
  if (connecticut_company_p[i] == "") {
    connecticut_company_p[i] <- NA
  }
}


state_name <- "Connecticut"
table_connecticut_company2 <- data.frame(connecticut_company_name, state_name, 
                                     connecticut_company_code, 
                                     connecticut_company_eup, connecticut_company_eor,
                                     connecticut_company_ec, connecticut_company_p)

colnames(table_connecticut_company2) = c("Company Name", "State", "Company Code", 
                                     "Electric Utility Plant (dollars)", 
                                     "Electric Operating Revenues (dollars)",
                                     "Electric Customers", 
                                     "Energy Purchased (Kilowatt/hour)")

write.csv (table_connecticut_company2, file = paste0('connecticut_table_company_1941', '.csv'))
```

