--- 
title: "Testing in District of Columbia" 
author: "Tri Truong" 
date: "6/3/2020" 
output:  
  pdf_document: default 
  html_document: default 
--- 
  
```{r setup, include=FALSE} 
knitr::opts_chunk$set(echo = TRUE, comment = NA,  
                      message = FALSE, warning = FALSE, 
                      fig.height=6, fig.width = 9, fig.align = "center") 
``` 
  
# Packages 
  
```{r load-packages, message = FALSE} 
library(stringr) 
library(dplyr) 
library(pdftools) 
library(tidyverse) 
library(pdftables) 
library(qpdf) 
library(rJava) 
library(tabulizer) 
library(tabulizerjars) 
``` 
  
# PDF 
  
```{r load_pdf_Alabama} 
pdf_subset("1941.Directory of electric utilities in the US pdf.pdf", page= 168:169, output= "District_of_Columbia_subset.pdf") 
``` 
  
  
```{r} 
district_of_columbia_file <- tabulizer::extract_text("District_of_columbia_subset.pdf") 
district_of_columbia_file2 <- str_split(district_of_columbia_file, "\n") 
district_of_columbia_file3 <- district_of_columbia_file2[[1]] 
final_district_of_columbia_file <- district_of_columbia_file3[1:length(district_of_columbia_file3)] 
``` 

  
```{r} 
vector_company <- vector(mode="character", length=11) 
  
company_position <- 1 
last_position <- 1 
track_vector <- 1 
tracking_data_frame <- 1 
  
district_of_columbia_company_code <- vector(mode="character") 
district_of_columbia_company_name <- vector(mode="character") 
district_of_columbia_company_eup <- vector(mode="character") 
district_of_columbia_company_eor <- vector(mode="character") 
district_of_columbia_company_ec <- vector(mode="character") 
district_of_columbia_company_p <- vector(mode="character") 
  
  
for (i in 3:length(final_district_of_columbia_file)) { 
    district_of_columbia_companies <- final_district_of_columbia_file 
     
    vector_company_copy <- vector(mode="character", length=1) 
     
    for (k in 1:length(district_of_columbia_companies)) { 
      if (str_detect(district_of_columbia_companies[k], '08-')) { 
        vector_company[track_vector] <- district_of_columbia_companies[k] 
        vector_company[track_vector+1] <- district_of_columbia_companies[k+1] 
        track_vector <- track_vector + 2 
         
        vector_company_copy[1] <- district_of_columbia_companies[k] 
        vector_company_copy[2] <- district_of_columbia_companies[k+1] 
      } 
       
      if (str_detect(district_of_columbia_companies[k], "Utility Plant")) { 
        
        if (str_detect(district_of_columbia_companies[k], "[0-9+]") == FALSE) {
          new_string <- paste(district_of_columbia_companies[k], district_of_columbia_companies[k+1])
        }
        else {
          new_string <- district_of_columbia_companies[k]
        }
        
        vector_company[track_vector] <- district_of_columbia_companies[k] 
        track_vector <- track_vector + 1 
         
        vector_company_copy[3] <- new_string
      } 
       
      if (str_detect(district_of_columbia_companies[k], "Operating Revenue")) { 
        
         if (str_detect(district_of_columbia_companies[k], "[0-9+]") == FALSE) {
          new_string <- paste(district_of_columbia_companies[k], district_of_columbia_companies[k+1])
        }
        else {
          new_string <- district_of_columbia_companies[k]
        }
        
        vector_company[track_vector] <- district_of_columbia_companies[k] 
        track_vector <- track_vector + 1 
         
        vector_company_copy[4] <- new_string
      } 
       
      if (str_detect(district_of_columbia_companies[k], "Customers")) { 
        
         if (str_detect(district_of_columbia_companies[k], "[0-9+]") == FALSE) {
          new_string <- paste(district_of_columbia_companies[k], district_of_columbia_companies[k+1])
        }
        else {
          new_string <- district_of_columbia_companies[k]
        }
        
        vector_company[track_vector] <- district_of_columbia_companies[k] 
        track_vector <- track_vector + 1 
         
        vector_company_copy[5] <- new_string 
      } 
       
      if(str_detect(district_of_columbia_companies[k], "Purchased")) { 
        
         if (str_detect(district_of_columbia_companies[k], "[0-9+]") == FALSE) {
          new_string <- paste(district_of_columbia_companies[k], district_of_columbia_companies[k+1])
        }
        else {
          new_string <- district_of_columbia_companies[k]
        }
        
        vector_company[track_vector] <- district_of_columbia_companies[k] 
        track_vector <- track_vector + 1 
         
        vector_company_copy[6] <- new_string 
      } 
    } 
    
    district_of_columbia_company_code[tracking_data_frame] <- vector_company_copy[1] 
    district_of_columbia_company_name[tracking_data_frame] <- vector_company_copy[2] 
     
    if(str_detect(vector_company_copy[3], "Utility Plant") & !is.na(vector_company_copy[3])) { 
      district_of_columbia_company_eup[tracking_data_frame] <- vector_company_copy[3] 
    } else { 
      district_of_columbia_company_eup[tracking_data_frame] <- NA 
    } 
     
   if(str_detect(vector_company_copy[4], "Operating Revenue") & !is.na(vector_company_copy[4])) { 
     district_of_columbia_company_eor[tracking_data_frame] <- vector_company_copy[4] 
   } else { 
     district_of_columbia_company_eor[tracking_data_frame] <- NA 
   } 
  
   if(str_detect(vector_company_copy[5], "Customers") & !is.na(vector_company_copy[5])) { 
     district_of_columbia_company_ec[tracking_data_frame] <- vector_company_copy[5] 
   } else { 
     district_of_columbia_company_ec[tracking_data_frame] <- NA 
   } 
  
   if(str_detect(vector_company_copy[6], "Purchased") & !is.na(vector_company_copy[6])) { 
     district_of_columbia_company_p[tracking_data_frame] <- vector_company_copy[6] 
   } else { 
     district_of_columbia_company_p[tracking_data_frame] <- NA 
   } 
  
    tracking_data_frame <- tracking_data_frame + 1 
    company_position <- company_position + 1 
    last_position <- i+1 
    break
} 
``` 
  
  
```{r} 
for (i in 1:length(district_of_columbia_company_code)) { 
  if (startsWith(district_of_columbia_company_code[i], "0") == FALSE) { 
    district_of_columbia_company_code[i] <- gsub("(?<=\\()[^()]*(?=\\))(*SKIP)(*F)|.", "",  
                                     district_of_columbia_company_code[i], perl=T) 
  } 
} 
  
for (i in 1:length(district_of_columbia_company_eup)) { 
  string <- district_of_columbia_company_eup[i] 
  string_vector <- str_split(string, "\\$") 
  district_of_columbia_company_eup[i] <- string_vector[[1]][2] 
} 
  
for (i in 1:length(district_of_columbia_company_eup)) { 
  string <- district_of_columbia_company_eup[i] 
  m <- gregexpr('[0-9]+',string) 
  something <- regmatches(string, m) 
  something <- c(something[[1]]) 
  district_of_columbia_company_eup[i] <- paste(something, collapse = '') 
} 
  
for (i in 1:length(district_of_columbia_company_eup)) { 
  if (district_of_columbia_company_eup[i] == "") { 
    district_of_columbia_company_eup[i] <- NA 
  } 
} 
  
for (i in 1:length(district_of_columbia_company_eor)) { 
  string <- district_of_columbia_company_eor[i] 
  string_vector <- str_split(string, "\\$") 
  district_of_columbia_company_eor[i] <- string_vector[[1]][2] 
} 
  
for (i in 1:length(district_of_columbia_company_eor)) { 
  string <- district_of_columbia_company_eor[i] 
  m <- gregexpr('[0-9]+',string) 
  something <- regmatches(string, m) 
  something <- c(something[[1]]) 
  district_of_columbia_company_eor[i] <- paste(something, collapse = '') 
} 
  
for (i in 1:length(district_of_columbia_company_eor)) { 
  if (district_of_columbia_company_eor[i] == "") { 
    district_of_columbia_company_eor[i] <- NA 
  } 
} 
  
  
for (i in 1:length(district_of_columbia_company_ec)) { 
  string <- district_of_columbia_company_ec[i] 
  m <- gregexpr('[0-9]+',string) 
  something <- regmatches(string, m) 
  something <- c(something[[1]]) 
  district_of_columbia_company_ec[i] <- paste(something, collapse = '') 
} 
  
for (i in 1:length(district_of_columbia_company_ec)) { 
  if (district_of_columbia_company_ec[i] == "") { 
    district_of_columbia_company_ec[i] <- NA 
  } 
} 

for (i in 1:length(district_of_columbia_company_p)) {
  string <- district_of_columbia_company_p[i]
  something <- gregexpr(pattern ='Purchased', string)
  something <- something[[1]]
  something <- something[1]
  district_of_columbia_company_p[i] <- substr(string, something, nchar(string))
}
  
  
for (i in 1:length(district_of_columbia_company_p)) { 
  string <- district_of_columbia_company_p[i] 
  m <- gregexpr('[0-9]+',string) 
  something <- regmatches(string, m) 
  something <- c(something[[1]]) 
  district_of_columbia_company_p[i] <- paste(something, collapse = '') 
} 
  
for (i in 1:length(district_of_columbia_company_p)) { 
  if (district_of_columbia_company_p[i] == "") { 
    district_of_columbia_company_p[i] <- NA 
  } 
} 
  
  
state_name <- "District of columbia" 
table_district_of_columbia_company2 <- data.frame(district_of_columbia_company_name, state_name,  
                                     district_of_columbia_company_code,  
                                     district_of_columbia_company_eup, district_of_columbia_company_eor, 
                                     district_of_columbia_company_ec, district_of_columbia_company_p) 
  
colnames(table_district_of_columbia_company2) = c("Company Name", "State", "Company Code",  
                                     "Electric Utility Plant (dollars)",  
                                     "Electric Operating Revenues (dollars)", 
                                     "Electric Customers",  
                                     "Energy Purchased (Kilowatt/hour)") 
  
write.csv (table_district_of_columbia_company2, file = paste0('district_of_columbia_table_company_1941', '.csv')) 
``` 
 
 