---   
title: "Testing in Massachusetts"   
author: "Tri Truong"   
date: "6/3/2020"   
output:    
  pdf_document: default   
  html_document: default   
---   
    
```{r setup, include=FALSE}   
knitr::opts_chunk$set(echo = TRUE, comment = NA,    
                      message = FALSE, warning = FALSE,   
                      fig.height=6, fig.width = 9, fig.align = "center")   
```   
    
# Packages   
    
```{r load-packages, message = FALSE}   
library(stringr)   
library(dplyr)   
library(pdftools)   
library(tidyverse)   
library(pdftables)   
library(qpdf)   
library(rJava)   
library(tabulizer)   
library(tabulizerjars)   
```   
    
# PDF   
    
```{r}   
pdf_subset("1941.Directory of electric utilities in the US pdf.pdf", page= 406:429, output= "Massachusetts_subset.pdf")   
```   
    
    
```{r}   
massachusetts_file <- tabulizer::extract_text("Massachusetts_subset.pdf")   
massachusetts_file2 <- str_split(massachusetts_file, "\n")   
massachusetts_file3 <- massachusetts_file2[[1]]   
final_massachusetts_file <- massachusetts_file3[119:length(massachusetts_file3)]   
```   
   
    
```{r}   
vector_company <- vector(mode="character", length=11)   
    
company_position <- 1   
last_position <- 1   
track_vector <- 1   
tracking_data_frame <- 1   
    
massachusetts_company_code <- vector(mode="character")   
massachusetts_company_name <- vector(mode="character")   
massachusetts_company_eup <- vector(mode="character")   
massachusetts_company_eor <- vector(mode="character")   
massachusetts_company_ec <- vector(mode="character")   
massachusetts_company_p <- vector(mode="character")   
    
    
for (i in 3:length(final_massachusetts_file)) {   
  if (str_detect(final_massachusetts_file[i], '20-')) {   
    massachusetts_companies <- final_massachusetts_file[last_position:i-1]   
       
    vector_company_copy <- vector(mode="character", length=1)   
       
    for (k in 1:length(massachusetts_companies)) {   
      if (str_detect(massachusetts_companies[k], '20-')) {   
        vector_company[track_vector] <- massachusetts_companies[k]   
        vector_company[track_vector+1] <- massachusetts_companies[k+1]   
        track_vector <- track_vector + 2   
           
        vector_company_copy[1] <- massachusetts_companies[k]   
        vector_company_copy[2] <- massachusetts_companies[k+1]   
      }   
         
      if (str_detect(massachusetts_companies[k], "Utility Plant")) { 
        
        if (str_detect(massachusetts_companies[k], "[0-9+]") == FALSE) {
          new_string <- paste(massachusetts_companies[k], massachusetts_companies[k+1])
        }
        else {
          new_string <- massachusetts_companies[k]
        }
        
        vector_company[track_vector] <- massachusetts_companies[k]   
        track_vector <- track_vector + 1   
           
        vector_company_copy[3] <- new_string  
      }   
         
      if (str_detect(massachusetts_companies[k], "Operating Revenue")) {  
        
        if (str_detect(massachusetts_companies[k], "[0-9+]") == FALSE) {
          new_string <- paste(massachusetts_companies[k], massachusetts_companies[k+1])
        }
        else {
          new_string <- massachusetts_companies[k]
        }
        
        vector_company[track_vector] <- massachusetts_companies[k]   
        track_vector <- track_vector + 1   
           
        vector_company_copy[4] <- new_string   
      }   
         
      if (str_detect(massachusetts_companies[k], "Customers")) { 
        
        if (str_detect(massachusetts_companies[k], "[0-9+]") == FALSE) {
          new_string <- paste(massachusetts_companies[k], massachusetts_companies[k+1])
        }
        else {
          new_string <- massachusetts_companies[k]
        }
        
        vector_company[track_vector] <- massachusetts_companies[k]   
        track_vector <- track_vector + 1   
           
        vector_company_copy[5] <- new_string 
      }   
         
      if(str_detect(massachusetts_companies[k], "Purchased")) {  
        
        if (str_detect(massachusetts_companies[k], "[0-9+]") == FALSE) {
          new_string <- paste(massachusetts_companies[k], massachusetts_companies[k+1])
        }
        else {
          new_string <- massachusetts_companies[k]
        }
        
        vector_company[track_vector] <- massachusetts_companies[k]   
        track_vector <- track_vector + 1   
           
        vector_company_copy[6] <- new_string 
      }   
    }   
      
    massachusetts_company_code[tracking_data_frame] <- vector_company_copy[1]   
    massachusetts_company_name[tracking_data_frame] <- vector_company_copy[2]   
       
    if(str_detect(vector_company_copy[3], "Utility Plant") & !is.na(vector_company_copy[3])) {   
      massachusetts_company_eup[tracking_data_frame] <- vector_company_copy[3]   
    } else {   
      massachusetts_company_eup[tracking_data_frame] <- NA   
    }   
       
   if(str_detect(vector_company_copy[4], "Operating Revenue") & !is.na(vector_company_copy[4])) {   
     massachusetts_company_eor[tracking_data_frame] <- vector_company_copy[4]   
   } else {   
     massachusetts_company_eor[tracking_data_frame] <- NA   
   }   
    
   if(str_detect(vector_company_copy[5], "Customers") & !is.na(vector_company_copy[5])) {   
     massachusetts_company_ec[tracking_data_frame] <- vector_company_copy[5]   
   } else {   
     massachusetts_company_ec[tracking_data_frame] <- NA   
   }   
    
   if(str_detect(vector_company_copy[6], "Purchased") & !is.na(vector_company_copy[6])) {   
     massachusetts_company_p[tracking_data_frame] <- vector_company_copy[6]   
   } else {   
     massachusetts_company_p[tracking_data_frame] <- NA   
   }   
    
    tracking_data_frame <- tracking_data_frame + 1   
    company_position <- company_position + 1   
    last_position <- i+1   
  }   
}   
```   
    
    
```{r}   
for (i in 1:length(massachusetts_company_code)) {   
  if (startsWith(massachusetts_company_code[i], "2") == FALSE) {   
    massachusetts_company_code[i] <- gsub("(?<=\\()[^()]*(?=\\))(*SKIP)(*F)|.", "",    
                                     massachusetts_company_code[i], perl=T)   
  }   
}   
    
for (i in 1:length(massachusetts_company_eup)) {   
  string <- massachusetts_company_eup[i]   
  string_vector <- str_split(string, "\\$")   
  massachusetts_company_eup[i] <- string_vector[[1]][2]   
}   
    
for (i in 1:length(massachusetts_company_eup)) {   
  string <- massachusetts_company_eup[i]   
  m <- gregexpr('[0-9]+',string)   
  something <- regmatches(string, m)   
  something <- c(something[[1]])   
  massachusetts_company_eup[i] <- paste(something, collapse = '')   
}   
    
for (i in 1:length(massachusetts_company_eup)) {   
  if (massachusetts_company_eup[i] == "") {   
    massachusetts_company_eup[i] <- NA   
  }   
}   
    
for (i in 1:length(massachusetts_company_eor)) {   
  string <- massachusetts_company_eor[i]   
  string_vector <- str_split(string, "\\$")   
  massachusetts_company_eor[i] <- string_vector[[1]][2]   
}   
    
for (i in 1:length(massachusetts_company_eor)) {   
  string <- massachusetts_company_eor[i]   
  m <- gregexpr('[0-9]+',string)   
  something <- regmatches(string, m)   
  something <- c(something[[1]])   
  massachusetts_company_eor[i] <- paste(something, collapse = '')   
}   
    
for (i in 1:length(massachusetts_company_eor)) {   
  if (massachusetts_company_eor[i] == "") {   
    massachusetts_company_eor[i] <- NA   
  }   
}   
    
    
for (i in 1:length(massachusetts_company_ec)) {   
  string <- massachusetts_company_ec[i]   
  m <- gregexpr('[0-9]+',string)   
  something <- regmatches(string, m)   
  something <- c(something[[1]])   
  massachusetts_company_ec[i] <- paste(something, collapse = '')   
}   
    
for (i in 1:length(massachusetts_company_ec)) {   
  if (massachusetts_company_ec[i] == "") {   
    massachusetts_company_ec[i] <- NA   
  }   
}   

for (i in 1:length(massachusetts_company_p)) {
  string <- massachusetts_company_p[i]
  something <- gregexpr(pattern ='Purchased', string)
  something <- something[[1]]
  something <- something[1]
  massachusetts_company_p[i] <- substr(string, something, nchar(string))
}
    
    
for (i in 1:length(massachusetts_company_p)) {   
  string <- massachusetts_company_p[i]   
  m <- gregexpr('[0-9]+',string)   
  something <- regmatches(string, m)   
  something <- c(something[[1]])   
  massachusetts_company_p[i] <- paste(something, collapse = '')   
}   
    
for (i in 1:length(massachusetts_company_p)) {   
  if (massachusetts_company_p[i] == "") {   
    massachusetts_company_p[i] <- NA   
  }   
}   
    
    
state_name <- "Massachusetts"   
table_massachusetts_company2 <- data.frame(massachusetts_company_name, state_name,    
                                     massachusetts_company_code,    
                                     massachusetts_company_eup, massachusetts_company_eor,   
                                     massachusetts_company_ec, massachusetts_company_p)   
    
colnames(table_massachusetts_company2) = c("Company Name", "State", "Company Code",    
                                     "Electric Utility Plant (dollars)",    
                                     "Electric Operating Revenues (dollars)",   
                                     "Electric Customers",    
                                     "Energy Purchased (Kilowatt/hour)")   
    
write.csv (table_massachusetts_company2, file = paste0('massachusetts_table_company_1941', '.csv'))   
```   
 
 