---
title: "Merging Files from Directory 1941"
author: "Tri Truong"
date: "6/4/2020"
output:         
  pdf_document: default        
  html_document: default        
---        
         
```{r setup, include=FALSE}        
knitr::opts_chunk$set(echo = TRUE, comment = NA,         
                      message = FALSE, warning = FALSE,        
                      fig.height=6, fig.width = 9, fig.align = "center")        
```        
         
# Packages        
         
```{r load-packages, message = FALSE}        
library(stringr)        
library(dplyr)        
library(pdftools)        
library(tidyverse)        
library(pdftables)        
library(qpdf)        
library(rJava)        
library(tabulizer)        
library(tabulizerjars)        
```        
         
# PDF   

```{r read_csv_file}
file1 <- read_csv("alabama_table_company_1941.csv")
file2 <- read_csv("arizona_table_company_1941.csv")
file3 <- read_csv("arkansas_table_company_1941.csv")
file4 <- read_csv("california_table_company_1941.csv")
file5 <- read_csv("colorado_table_company_1941.csv")
file6 <- read_csv("connecticut_table_company_1941.csv")
file7 <- read_csv("delaware_table_company_1941.csv")
file8 <- read_csv("district_of_columbia_table_company_1941.csv")
file9 <- read_csv("florida_table_company_1941.csv")
file10 <- read_csv("georgia_table_company_1941.csv")
file11 <- read_csv("idaho_table_company_1941.csv")
file12 <- read_csv("illinois_table_company_1941.csv")
file13 <- read_csv("indiana_table_company_1941.csv")
file14 <- read_csv("iowa_table_company_1941.csv")
file15 <- read_csv("kansas_table_company_1941.csv")
file16 <- read_csv("kentucky_table_company_1941.csv")
file17 <- read_csv("louisiana_table_company_1941.csv")
file18 <- read_csv("maine_table_company_1941.csv")
file19 <- read_csv("maryland_table_company_1941.csv")
file20 <- read_csv("massachusetts_table_company_1941.csv")
file21 <- read_csv("michigan_table_company_1941.csv")
file22 <- read_csv("minnesota_table_company_1941.csv")
file23 <- read_csv("mississippi_table_company_1941.csv")
file24 <- read_csv("missouri_table_company_1941.csv")
file25 <- read_csv("montana_table_company_1941.csv")
file26 <- read_csv("nebraska_table_company_1941.csv")
file27 <- read_csv("nevada_table_company_1941.csv")
file28 <- read_csv("new_hampshire_table_company_1941.csv")
file29 <- read_csv("new_jersey_table_company_1941.csv")
file30 <- read_csv("new_mexico_table_company_1941.csv")
file31 <- read_csv("new_york_table_company_1941.csv")
file32 <- read_csv("north_carolina_table_company_1941.csv")
file33 <- read_csv("north_dakota_table_company_1941.csv")
file34 <- read_csv("ohio_table_company_1941.csv")
file35 <- read_csv("oklahoma_table_company_1941.csv")
file36 <- read_csv("oregon_table_company_1941.csv")
file37 <- read_csv("pennsylvania_table_company_1941.csv")
file38 <- read_csv("rhode_island_table_company_1941.csv")
file39 <- read_csv("south_carolina_table_company_1941.csv")
file40 <- read_csv("south_dakota_table_company_1941.csv")
file41 <- read_csv("tennessee_table_company_1941.csv")
file42 <- read_csv("texas_table_company_1941.csv")
file43 <- read_csv("utah_table_company_1941.csv")
file44 <- read_csv("vermont_table_company_1941.csv")
file45 <- read_csv("virginia_table_company_1941.csv")
file46 <- read_csv("washington_table_company_1941.csv")
file47 <- read_csv("west_virginia_table_company_1941.csv")
file48 <- read_csv("wisconsin_table_company_1941.csv")
file49 <- read_csv("wyoming_table_company_1941.csv")
```

```{r}
final_file <- rbind(
file1,
file2,
file3,
file4,
file5,
file6,
file7,
file8,
file9,
file10,
file11,
file12,
file13,
file14,
file15,
file16,
file17,
file18,
file19,
file20,
file21,
file22,
file23,
file24,
file25,
file26,
file27,
file28,
file29,
file30,
file31,
file32,
file33,
file34,
file35,
file36,
file37,
file38,
file39,
file40,
file41,
file42,
file43,
file44,
file45,
file46,
file47,
file48,
file49
)
```

```{r}
new_england_file <- rbind(file6, file20, file28, file18, file44, file38)
mid_atlantic_file <- rbind(file7, file29, file31, file37)
atlantic_coast_appalachian_file <- rbind(file16, file19, file32, file41, file45, file47)
southeast_gulf_file <- rbind(file1, file9, file10, file23, file39)
south_central_file <- rbind(file3, file17, file35, file42)
great_lake_file <- rbind(file12, file13, file21, file22, file34, file48)
plains_file <- rbind(file14, file15, file24, file26, file33, file40)
mountain_file <- rbind(file5, file11, file25, file43, file49)
southwest_desert_file <- rbind(file2, file27, file30)
pacific_file <- rbind(file4, file36, file46)
```


```{r}
final_file$X1 <- NULL
new_england_file$X1 <- NULL
atlantic_coast_appalachian_file$X1 <- NULL
mid_atlantic_file$X1 <- NULL
southeast_gulf_file$X1 <- NULL
south_central_file$X1 <- NULL
great_lake_file$X1 <- NULL
plains_file$X1<- NULL
mountain_file$X1 <- NULL
southwest_desert_file$X1 <- NULL
pacific_file$X1 <- NULL
```


```{r}
write.csv (final_file, file = paste0('1941_Directory_of_electric_utilities_in_the_US', '.csv'))
write.csv(new_england_file, file = paste0('1941_Directory_of_electric_utilities_in_New_England', '.csv'))
write.csv(mid_atlantic_file, file = paste0('1941_Directory_of_electric_utilities_in_Mid_Alantic', '.csv'))
write.csv(atlantic_coast_appalachian_file, file = paste0('1941_Directory_of_electric_utilities_in_Atlantic_Coast_Appalachian', '.csv'))
write.csv (southeast_gulf_file, file = paste0('1941_Directory_of_electric_utilities_in_Southeast_Gulf', '.csv'))
write.csv (south_central_file, file = paste0('1941_Directory_of_electric_utilities_in_South_Central', '.csv'))
write.csv (great_lake_file, file = paste0('1941_Directory_of_electric_utilities_in_Great_Lake', '.csv'))
write.csv (plains_file, file = paste0('1941_Directory_of_electric_utilities_in_Plains', '.csv'))
write.csv (mountain_file, file = paste0('1941_Directory_of_electric_utilities_in_Mountain', '.csv'))
write.csv (southwest_desert_file, file = paste0('1941_Directory_of_electric_utilities_in_Southwest_Desert', '.csv'))
write.csv (pacific_file, file = paste0('1941_Directory_of_electric_utilities_in_Pacific', '.csv'))
```




