---    
title: "Testing in Minnesota"    
author: "Tri Truong"    
date: "6/4/2020"    
output:     
  pdf_document: default    
  html_document: default    
---    
     
```{r setup, include=FALSE}    
knitr::opts_chunk$set(echo = TRUE, comment = NA,     
                      message = FALSE, warning = FALSE,    
                      fig.height=6, fig.width = 9, fig.align = "center")    
```    
     
# Packages    
     
```{r load-packages, message = FALSE}    
library(stringr)    
library(dplyr)    
library(pdftools)    
library(tidyverse)    
library(pdftables)    
library(qpdf)    
library(rJava)    
library(tabulizer)    
library(tabulizerjars)    
```    
     
# PDF    
     
```{r}    
pdf_subset("1941.Directory of electric utilities in the US pdf.pdf", page= 454:491, output= "Minnesota_subset.pdf")    
```    
     
     
```{r}    
minnesota_file <- tabulizer::extract_text("Minnesota_subset.pdf")    
minnesota_file2 <- str_split(minnesota_file, "\n")    
minnesota_file3 <- minnesota_file2[[1]]    
final_minnesota_file <- minnesota_file3[332:length(minnesota_file3)]    
```    

    
     
```{r}    
vector_company <- vector(mode="character", length=11)    
     
company_position <- 1    
last_position <- 1    
track_vector <- 1    
tracking_data_frame <- 1    
     
minnesota_company_code <- vector(mode="character")    
minnesota_company_name <- vector(mode="character")    
minnesota_company_eup <- vector(mode="character")    
minnesota_company_eor <- vector(mode="character")    
minnesota_company_ec <- vector(mode="character")    
minnesota_company_p <- vector(mode="character")    
     
     
for (i in 3:length(final_minnesota_file)) {    
  if (str_detect(final_minnesota_file[i], '22-')) {    
    minnesota_companies <- final_minnesota_file[last_position:i-1]    
        
    vector_company_copy <- vector(mode="character", length=1)    
        
    for (k in 1:length(minnesota_companies)) {    
      if (str_detect(minnesota_companies[k], '22-')) {    
        vector_company[track_vector] <- minnesota_companies[k]    
        vector_company[track_vector+1] <- minnesota_companies[k+1]    
        track_vector <- track_vector + 2    
            
        vector_company_copy[1] <- minnesota_companies[k]    
        vector_company_copy[2] <- minnesota_companies[k+1]    
      }    
          
      if (str_detect(minnesota_companies[k], "Utility Plant")) {   
        
        if (str_detect(minnesota_companies[k], "[0-9+]") == FALSE) {
          new_string <- paste(minnesota_companies[k], minnesota_companies[k+1])
        }
        else {
          new_string <- minnesota_companies[k]
        }
        
        vector_company[track_vector] <- minnesota_companies[k]    
        track_vector <- track_vector + 1    
            
        vector_company_copy[3] <- new_string    
      }    
          
      if (str_detect(minnesota_companies[k], "Operating Revenue")) {   
        
        if (str_detect(minnesota_companies[k], "[0-9+]") == FALSE) {
          new_string <- paste(minnesota_companies[k], minnesota_companies[k+1])
        }
        else {
          new_string <- minnesota_companies[k]
        }
        
        vector_company[track_vector] <- minnesota_companies[k]    
        track_vector <- track_vector + 1    
            
        vector_company_copy[4] <- new_string   
      }    
          
      if (str_detect(minnesota_companies[k], "Customers")) {    
        
        if (str_detect(minnesota_companies[k], "[0-9+]") == FALSE) {
          new_string <- paste(minnesota_companies[k], minnesota_companies[k+1])
        }
        else {
          new_string <- minnesota_companies[k]
        }
        
        vector_company[track_vector] <- minnesota_companies[k]    
        track_vector <- track_vector + 1    
            
        vector_company_copy[5] <- new_string  
      }    
          
      if(str_detect(minnesota_companies[k], "Purchased")) {    
        
        if (str_detect(minnesota_companies[k], "[0-9+]") == FALSE) {
          new_string <- paste(minnesota_companies[k], minnesota_companies[k+1])
        }
        else {
          new_string <- minnesota_companies[k]
        }
        
        vector_company[track_vector] <- minnesota_companies[k]    
        track_vector <- track_vector + 1    
            
        vector_company_copy[6] <- new_string   
      }    
    }    
       
    minnesota_company_code[tracking_data_frame] <- vector_company_copy[1]    
    minnesota_company_name[tracking_data_frame] <- vector_company_copy[2]    
        
    if(str_detect(vector_company_copy[3], "Utility Plant") & !is.na(vector_company_copy[3])) {    
      minnesota_company_eup[tracking_data_frame] <- vector_company_copy[3]    
    } else {    
      minnesota_company_eup[tracking_data_frame] <- NA    
    }    
        
   if(str_detect(vector_company_copy[4], "Operating Revenue") & !is.na(vector_company_copy[4])) {    
     minnesota_company_eor[tracking_data_frame] <- vector_company_copy[4]    
   } else {    
     minnesota_company_eor[tracking_data_frame] <- NA    
   }    
     
   if(str_detect(vector_company_copy[5], "Customers") & !is.na(vector_company_copy[5])) {    
     minnesota_company_ec[tracking_data_frame] <- vector_company_copy[5]    
   } else {    
     minnesota_company_ec[tracking_data_frame] <- NA    
   }    
     
   if(str_detect(vector_company_copy[6], "Purchased") & !is.na(vector_company_copy[6])) {    
     minnesota_company_p[tracking_data_frame] <- vector_company_copy[6]    
   } else {    
     minnesota_company_p[tracking_data_frame] <- NA    
   }    
     
    tracking_data_frame <- tracking_data_frame + 1    
    company_position <- company_position + 1    
    last_position <- i+1    
  }    
}    
```    
     
     
```{r}    
for (i in 1:length(minnesota_company_code)) {    
  if (startsWith(minnesota_company_code[i], "2") == FALSE) {    
    minnesota_company_code[i] <- gsub("(?<=\\()[^()]*(?=\\))(*SKIP)(*F)|.", "",     
                                     minnesota_company_code[i], perl=T)    
  }    
}    
     
for (i in 1:length(minnesota_company_eup)) {    
  string <- minnesota_company_eup[i]    
  string_vector <- str_split(string, "\\$")    
  minnesota_company_eup[i] <- string_vector[[1]][2]    
}    
     
for (i in 1:length(minnesota_company_eup)) {    
  string <- minnesota_company_eup[i]    
  m <- gregexpr('[0-9]+',string)    
  something <- regmatches(string, m)    
  something <- c(something[[1]])    
  minnesota_company_eup[i] <- paste(something, collapse = '')    
}    
     
for (i in 1:length(minnesota_company_eup)) {    
  if (minnesota_company_eup[i] == "") {    
    minnesota_company_eup[i] <- NA    
  }    
}    
     
for (i in 1:length(minnesota_company_eor)) {    
  string <- minnesota_company_eor[i]    
  string_vector <- str_split(string, "\\$")    
  minnesota_company_eor[i] <- string_vector[[1]][2]    
}    
     
for (i in 1:length(minnesota_company_eor)) {    
  string <- minnesota_company_eor[i]    
  m <- gregexpr('[0-9]+',string)    
  something <- regmatches(string, m)    
  something <- c(something[[1]])    
  minnesota_company_eor[i] <- paste(something, collapse = '')    
}    
     
for (i in 1:length(minnesota_company_eor)) {    
  if (minnesota_company_eor[i] == "") {    
    minnesota_company_eor[i] <- NA    
  }    
}    
     
     
for (i in 1:length(minnesota_company_ec)) {    
  string <- minnesota_company_ec[i]    
  m <- gregexpr('[0-9]+',string)    
  something <- regmatches(string, m)    
  something <- c(something[[1]])    
  minnesota_company_ec[i] <- paste(something, collapse = '')    
}    
     
for (i in 1:length(minnesota_company_ec)) {    
  if (minnesota_company_ec[i] == "") {    
    minnesota_company_ec[i] <- NA    
  }    
}    
     
for (i in 1:length(minnesota_company_p)) {
  string <- minnesota_company_p[i]
  something <- gregexpr(pattern ='Purchased', string)
  something <- something[[1]]
  something <- something[1]
  minnesota_company_p[i] <- substr(string, something, nchar(string))
}
     
for (i in 1:length(minnesota_company_p)) {    
  string <- minnesota_company_p[i]    
  m <- gregexpr('[0-9]+',string)    
  something <- regmatches(string, m)    
  something <- c(something[[1]])    
  minnesota_company_p[i] <- paste(something, collapse = '')    
}    
     
for (i in 1:length(minnesota_company_p)) {    
  if (minnesota_company_p[i] == "") {    
    minnesota_company_p[i] <- NA    
  }    
}    
     
     
state_name <- "Minnesota"    
table_minnesota_company2 <- data.frame(minnesota_company_name, state_name,     
                                     minnesota_company_code,     
                                     minnesota_company_eup, minnesota_company_eor,    
                                     minnesota_company_ec, minnesota_company_p)    
     
colnames(table_minnesota_company2) = c("Company Name", "State", "Company Code",     
                                     "Electric Utility Plant (dollars)",     
                                     "Electric Operating Revenues (dollars)",    
                                     "Electric Customers",     
                                     "Energy Purchased (Kilowatt/hour)")    
     
write.csv (table_minnesota_company2, file = paste0('minnesota_table_company_1941', '.csv'))    
```    
 
 