---       
title: "Testing in South_carolina"       
author: "Tri Truong"       
date: "6/4/2020"       
output:        
  pdf_document: default       
  html_document: default       
---       
        
```{r setup, include=FALSE}       
knitr::opts_chunk$set(echo = TRUE, comment = NA,        
                      message = FALSE, warning = FALSE,       
                      fig.height=6, fig.width = 9, fig.align = "center")       
```       
        
# Packages       
        
```{r load-packages, message = FALSE}       
library(stringr)       
library(dplyr)       
library(pdftools)       
library(tidyverse)       
library(pdftables)       
library(qpdf)       
library(rJava)       
library(tabulizer)       
library(tabulizerjars)       
```       
        
# PDF       
        
```{r}       
pdf_subset("1941.Directory of electric utilities in the US pdf.pdf", page= 796:807, output= "South_carolina_subset.pdf")       
```       
        
        
```{r}       
south_carolina_file <- tabulizer::extract_text("South_carolina_subset.pdf")       
south_carolina_file2 <- str_split(south_carolina_file, "\n")       
south_carolina_file3 <- south_carolina_file2[[1]]       
final_south_carolina_file <- south_carolina_file3[76:length(south_carolina_file3)]       
```       
    
       
        
```{r}       
vector_company <- vector(mode="character", length=11)       
        
company_position <- 1       
last_position <- 1       
track_vector <- 1       
tracking_data_frame <- 1       
        
south_carolina_company_code <- vector(mode="character")       
south_carolina_company_name <- vector(mode="character")       
south_carolina_company_eup <- vector(mode="character")       
south_carolina_company_eor <- vector(mode="character")       
south_carolina_company_ec <- vector(mode="character")       
south_carolina_company_p <- vector(mode="character")       
        
        
for (i in 3:length(final_south_carolina_file)) {       
  if (str_detect(final_south_carolina_file[i], '39-')) {       
    south_carolina_companies <- final_south_carolina_file[last_position:i-1]       
           
    vector_company_copy <- vector(mode="character", length=1)       
           
    for (k in 1:length(south_carolina_companies)) {       
      if (str_detect(south_carolina_companies[k], '39-')) {       
        vector_company[track_vector] <- south_carolina_companies[k]       
        vector_company[track_vector+1] <- south_carolina_companies[k+1]       
        track_vector <- track_vector + 2       
               
        vector_company_copy[1] <- south_carolina_companies[k]       
        vector_company_copy[2] <- south_carolina_companies[k+1]       
      }       
             
      if (str_detect(south_carolina_companies[k], "Utility Plant")) {       
        
        if (str_detect(south_carolina_companies[k], "[0-9+]") == FALSE) {
          new_string <- paste(south_carolina_companies[k], south_carolina_companies[k+1])
        }
        else {
          new_string <- south_carolina_companies[k]
        }
        
        vector_company[track_vector] <- south_carolina_companies[k]       
        track_vector <- track_vector + 1       
               
        vector_company_copy[3] <- new_string      
      }       
             
      if (str_detect(south_carolina_companies[k], "Operating Revenue")) {    
        
        if (str_detect(south_carolina_companies[k], "[0-9+]") == FALSE) {
          new_string <- paste(south_carolina_companies[k], south_carolina_companies[k+1])
        }
        else {
          new_string <- south_carolina_companies[k]
        }
        
        vector_company[track_vector] <- south_carolina_companies[k]       
        track_vector <- track_vector + 1       
               
        vector_company_copy[4] <- new_string      
      }       
             
      if (str_detect(south_carolina_companies[k], "Customers")) {    
        
        if (str_detect(south_carolina_companies[k], "[0-9+]") == FALSE) {
          new_string <- paste(south_carolina_companies[k], south_carolina_companies[k+1])
        }
        else {
          new_string <- south_carolina_companies[k]
        }
        
        vector_company[track_vector] <- south_carolina_companies[k]       
        track_vector <- track_vector + 1       
               
        vector_company_copy[5] <- new_string      
      }       
             
      if(str_detect(south_carolina_companies[k], "Purchased")) {     
        
        if (str_detect(south_carolina_companies[k], "[0-9+]") == FALSE) {
          new_string <- paste(south_carolina_companies[k], south_carolina_companies[k+1])
        }
        else {
          new_string <- south_carolina_companies[k]
        }
        
        vector_company[track_vector] <- south_carolina_companies[k]       
        track_vector <- track_vector + 1       
               
        vector_company_copy[6] <- new_string      
      }       
    }       
          
    south_carolina_company_code[tracking_data_frame] <- vector_company_copy[1]       
    south_carolina_company_name[tracking_data_frame] <- vector_company_copy[2]       
           
    if(str_detect(vector_company_copy[3], "Utility Plant") & !is.na(vector_company_copy[3])) {       
      south_carolina_company_eup[tracking_data_frame] <- vector_company_copy[3]       
    } else {       
      south_carolina_company_eup[tracking_data_frame] <- NA       
    }       
           
   if(str_detect(vector_company_copy[4], "Operating Revenue") & !is.na(vector_company_copy[4])) {       
     south_carolina_company_eor[tracking_data_frame] <- vector_company_copy[4]       
   } else {       
     south_carolina_company_eor[tracking_data_frame] <- NA       
   }       
        
   if(str_detect(vector_company_copy[5], "Customers") & !is.na(vector_company_copy[5])) {       
     south_carolina_company_ec[tracking_data_frame] <- vector_company_copy[5]       
   } else {       
     south_carolina_company_ec[tracking_data_frame] <- NA       
   }       
        
   if(str_detect(vector_company_copy[6], "Purchased") & !is.na(vector_company_copy[6])) {       
     south_carolina_company_p[tracking_data_frame] <- vector_company_copy[6]       
   } else {       
     south_carolina_company_p[tracking_data_frame] <- NA       
   }       
        
    tracking_data_frame <- tracking_data_frame + 1       
    company_position <- company_position + 1       
    last_position <- i+1       
  }       
}       
```       
        
```{r} 
for(i in 1:length(south_carolina_company_code)) { 
  if (startsWith(south_carolina_company_code[i], "3")) { 
    south_carolina_company_code[i] <- substr(south_carolina_company_code[i], 1, 7) 
  } 
} 
``` 
        
        
```{r}       
for (i in 1:length(south_carolina_company_code)) {       
  if (startsWith(south_carolina_company_code[i], "3") == FALSE) {       
    south_carolina_company_code[i] <- gsub("(?<=\\()[^()]*(?=\\))(*SKIP)(*F)|.", "",        
                                     south_carolina_company_code[i], perl=T)       
  }       
}       
        
for (i in 1:length(south_carolina_company_eup)) {       
  string <- south_carolina_company_eup[i]       
  string_vector <- str_split(string, "\\$")       
  south_carolina_company_eup[i] <- string_vector[[1]][2]       
}       
        
for (i in 1:length(south_carolina_company_eup)) {       
  string <- south_carolina_company_eup[i]       
  m <- gregexpr('[0-9]+',string)       
  something <- regmatches(string, m)       
  something <- c(something[[1]])       
  south_carolina_company_eup[i] <- paste(something, collapse = '')       
}       
        
for (i in 1:length(south_carolina_company_eup)) {       
  if (south_carolina_company_eup[i] == "") {       
    south_carolina_company_eup[i] <- NA       
  }       
}       
        
for (i in 1:length(south_carolina_company_eor)) {       
  string <- south_carolina_company_eor[i]       
  string_vector <- str_split(string, "\\$")       
  south_carolina_company_eor[i] <- string_vector[[1]][2]       
}       
        
for (i in 1:length(south_carolina_company_eor)) {       
  string <- south_carolina_company_eor[i]       
  m <- gregexpr('[0-9]+',string)       
  something <- regmatches(string, m)       
  something <- c(something[[1]])       
  south_carolina_company_eor[i] <- paste(something, collapse = '')       
}       
        
for (i in 1:length(south_carolina_company_eor)) {       
  if (south_carolina_company_eor[i] == "") {       
    south_carolina_company_eor[i] <- NA       
  }       
}       
        
        
for (i in 1:length(south_carolina_company_ec)) {       
  string <- south_carolina_company_ec[i]       
  m <- gregexpr('[0-9]+',string)       
  something <- regmatches(string, m)       
  something <- c(something[[1]])       
  south_carolina_company_ec[i] <- paste(something, collapse = '')       
}       
        
for (i in 1:length(south_carolina_company_ec)) {       
  if (south_carolina_company_ec[i] == "") {       
    south_carolina_company_ec[i] <- NA       
  }       
}       
        
for (i in 1:length(south_carolina_company_p)) {
  string <- south_carolina_company_p[i]
  something <- gregexpr(pattern ='Purchased', string)
  something <- something[[1]]
  something <- something[1]
  south_carolina_company_p[i] <- substr(string, something, nchar(string))
}
        
for (i in 1:length(south_carolina_company_p)) {       
  string <- south_carolina_company_p[i]       
  m <- gregexpr('[0-9]+',string)       
  something <- regmatches(string, m)       
  something <- c(something[[1]])       
  south_carolina_company_p[i] <- paste(something, collapse = '')       
}       
        
for (i in 1:length(south_carolina_company_p)) {       
  if (south_carolina_company_p[i] == "") {       
    south_carolina_company_p[i] <- NA       
  }       
}       
        
        
state_name <- "South Carolina"       
table_south_carolina_company2 <- data.frame(south_carolina_company_name, state_name,        
                                     south_carolina_company_code,        
                                     south_carolina_company_eup, south_carolina_company_eor,       
                                     south_carolina_company_ec, south_carolina_company_p)       
        
colnames(table_south_carolina_company2) = c("Company Name", "State", "Company Code",        
                                     "Electric Utility Plant (dollars)",        
                                     "Electric Operating Revenues (dollars)",       
                                     "Electric Customers",        
                                     "Energy Purchased (Kilowatt/hour)")       
        
write.csv (table_south_carolina_company2, file = paste0('south_carolina_table_company_1941', '.csv'))       
```       
 
 