---        
title: "Testing in Vermont"        
author: "Tri Truong"        
date: "6/4/2020"        
output:         
  pdf_document: default        
  html_document: default        
---        
         
```{r setup, include=FALSE}        
knitr::opts_chunk$set(echo = TRUE, comment = NA,         
                      message = FALSE, warning = FALSE,        
                      fig.height=6, fig.width = 9, fig.align = "center")        
```        
         
# Packages        
         
```{r load-packages, message = FALSE}        
library(stringr)        
library(dplyr)        
library(pdftools)        
library(tidyverse)        
library(pdftables)        
library(qpdf)        
library(rJava)        
library(tabulizer)        
library(tabulizerjars)        
```        
         
# PDF        
         
```{r}        
pdf_subset("1941.Directory of electric utilities in the US pdf.pdf", page= 888:897, output= "Vermont_subset.pdf")        
```        
         
         
```{r}        
vermont_file <- tabulizer::extract_text("Vermont_subset.pdf")        
vermont_file2 <- str_split(vermont_file, "\n")        
vermont_file3 <- vermont_file2[[1]]        
final_vermont_file <- vermont_file3[87:length(vermont_file3)]        
```        
     
   
         
```{r}        
vector_company <- vector(mode="character", length=11)        
         
company_position <- 1        
last_position <- 1        
track_vector <- 1        
tracking_data_frame <- 1        
         
vermont_company_code <- vector(mode="character")        
vermont_company_name <- vector(mode="character")        
vermont_company_eup <- vector(mode="character")        
vermont_company_eor <- vector(mode="character")        
vermont_company_ec <- vector(mode="character")        
vermont_company_p <- vector(mode="character")        
         
         
for (i in 3:length(final_vermont_file)) {        
  if (str_detect(final_vermont_file[i], '44-')) {        
    vermont_companies <- final_vermont_file[last_position:i-1]        
            
    vector_company_copy <- vector(mode="character", length=1)        
            
    for (k in 1:length(vermont_companies)) {        
      if (str_detect(vermont_companies[k], '44-')) {        
        vector_company[track_vector] <- vermont_companies[k]        
        vector_company[track_vector+1] <- vermont_companies[k+1]        
        track_vector <- track_vector + 2        
                
        vector_company_copy[1] <- vermont_companies[k]        
        vector_company_copy[2] <- vermont_companies[k+1]        
      }        
              
      if (str_detect(vermont_companies[k], "Utility Plant")) {  
        
        if (str_detect(vermont_companies[k], "[0-9+]") == FALSE) {
          new_string <- paste(vermont_companies[k], vermont_companies[k+1])
        }
        else {
          new_string <- vermont_companies[k]
        }
        
        vector_company[track_vector] <- vermont_companies[k]        
        track_vector <- track_vector + 1        
                
        vector_company_copy[3] <- new_string       
      }        
              
      if (str_detect(vermont_companies[k], "Operating Revenue")) { 
        
        if (str_detect(vermont_companies[k], "[0-9+]") == FALSE) {
          new_string <- paste(vermont_companies[k], vermont_companies[k+1])
        }
        else {
          new_string <- vermont_companies[k]
        }
        
        vector_company[track_vector] <- vermont_companies[k]        
        track_vector <- track_vector + 1        
                
        vector_company_copy[4] <- new_string       
      }        
              
      if (str_detect(vermont_companies[k], "Customers")) {   
        
        if (str_detect(vermont_companies[k], "[0-9+]") == FALSE) {
          new_string <- paste(vermont_companies[k], vermont_companies[k+1])
        }
        else {
          new_string <- vermont_companies[k]
        }
        
        vector_company[track_vector] <- vermont_companies[k]        
        track_vector <- track_vector + 1        
                
        vector_company_copy[5] <- new_string       
      }        
              
      if(str_detect(vermont_companies[k], "Purchased")) {   
        
        if (str_detect(vermont_companies[k], "[0-9+]") == FALSE) {
          new_string <- paste(vermont_companies[k], vermont_companies[k+1])
        }
        else {
          new_string <- vermont_companies[k]
        }
        
        vector_company[track_vector] <- vermont_companies[k]        
        track_vector <- track_vector + 1        
                
        vector_company_copy[6] <- new_string       
      }        
    }        
           
    vermont_company_code[tracking_data_frame] <- vector_company_copy[1]        
    vermont_company_name[tracking_data_frame] <- vector_company_copy[2]        
            
    if(str_detect(vector_company_copy[3], "Utility Plant") & !is.na(vector_company_copy[3])) {        
      vermont_company_eup[tracking_data_frame] <- vector_company_copy[3]        
    } else {        
      vermont_company_eup[tracking_data_frame] <- NA        
    }        
            
   if(str_detect(vector_company_copy[4], "Operating Revenue") & !is.na(vector_company_copy[4])) {        
     vermont_company_eor[tracking_data_frame] <- vector_company_copy[4]        
   } else {        
     vermont_company_eor[tracking_data_frame] <- NA        
   }        
         
   if(str_detect(vector_company_copy[5], "Customers") & !is.na(vector_company_copy[5])) {        
     vermont_company_ec[tracking_data_frame] <- vector_company_copy[5]        
   } else {        
     vermont_company_ec[tracking_data_frame] <- NA        
   }        
         
   if(str_detect(vector_company_copy[6], "Purchased") & !is.na(vector_company_copy[6])) {        
     vermont_company_p[tracking_data_frame] <- vector_company_copy[6]        
   } else {        
     vermont_company_p[tracking_data_frame] <- NA        
   }        
         
    tracking_data_frame <- tracking_data_frame + 1        
    company_position <- company_position + 1        
    last_position <- i+1        
  }        
}        
```        
         
```{r}  
for(i in 1:length(vermont_company_code)) {  
  if (startsWith(vermont_company_code[i], "4")) {  
    vermont_company_code[i] <- substr(vermont_company_code[i], 1, 7)  
  }  
}  
```  
         
         
```{r}        
for (i in 1:length(vermont_company_code)) {        
  if (startsWith(vermont_company_code[i], "4") == FALSE) {        
    vermont_company_code[i] <- gsub("(?<=\\()[^()]*(?=\\))(*SKIP)(*F)|.", "",         
                                     vermont_company_code[i], perl=T)        
  }        
}        
         
for (i in 1:length(vermont_company_eup)) {        
  string <- vermont_company_eup[i]        
  string_vector <- str_split(string, "\\$")        
  vermont_company_eup[i] <- string_vector[[1]][2]        
}        
         
for (i in 1:length(vermont_company_eup)) {        
  string <- vermont_company_eup[i]        
  m <- gregexpr('[0-9]+',string)        
  something <- regmatches(string, m)        
  something <- c(something[[1]])        
  vermont_company_eup[i] <- paste(something, collapse = '')        
}        
         
for (i in 1:length(vermont_company_eup)) {        
  if (vermont_company_eup[i] == "") {        
    vermont_company_eup[i] <- NA        
  }        
}        
         
for (i in 1:length(vermont_company_eor)) {        
  string <- vermont_company_eor[i]        
  string_vector <- str_split(string, "\\$")        
  vermont_company_eor[i] <- string_vector[[1]][2]        
}        
         
for (i in 1:length(vermont_company_eor)) {        
  string <- vermont_company_eor[i]        
  m <- gregexpr('[0-9]+',string)        
  something <- regmatches(string, m)        
  something <- c(something[[1]])        
  vermont_company_eor[i] <- paste(something, collapse = '')        
}        
         
for (i in 1:length(vermont_company_eor)) {        
  if (vermont_company_eor[i] == "") {        
    vermont_company_eor[i] <- NA        
  }        
}        
         
         
for (i in 1:length(vermont_company_ec)) {        
  string <- vermont_company_ec[i]        
  m <- gregexpr('[0-9]+',string)        
  something <- regmatches(string, m)        
  something <- c(something[[1]])        
  vermont_company_ec[i] <- paste(something, collapse = '')        
}        
         
for (i in 1:length(vermont_company_ec)) {        
  if (vermont_company_ec[i] == "") {        
    vermont_company_ec[i] <- NA        
  }        
}        
       
for (i in 1:length(vermont_company_p)) {
  string <- vermont_company_p[i]
  something <- gregexpr(pattern ='Purchased', string)
  something <- something[[1]]
  something <- something[1]
  vermont_company_p[i] <- substr(string, something, nchar(string))
}
         
for (i in 1:length(vermont_company_p)) {        
  string <- vermont_company_p[i]        
  m <- gregexpr('[0-9]+',string)        
  something <- regmatches(string, m)        
  something <- c(something[[1]])        
  vermont_company_p[i] <- paste(something, collapse = '')        
}        
         
for (i in 1:length(vermont_company_p)) {        
  if (vermont_company_p[i] == "") {        
    vermont_company_p[i] <- NA        
  }        
}        
         
         
state_name <- "Vermont"        
table_vermont_company2 <- data.frame(vermont_company_name, state_name,         
                                     vermont_company_code,         
                                     vermont_company_eup, vermont_company_eor,        
                                     vermont_company_ec, vermont_company_p)        
         
colnames(table_vermont_company2) = c("Company Name", "State", "Company Code",         
                                     "Electric Utility Plant (dollars)",         
                                     "Electric Operating Revenues (dollars)",        
                                     "Electric Customers",         
                                     "Energy Purchased (Kilowatt/hour)")        
         
write.csv (table_vermont_company2, file = paste0('vermont_table_company_1941', '.csv'))        
```        
 
 